{% set name = "sqlglotrs" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlglotrs-{{ version }}.tar.gz
  sha256: caadc572c8a194f99d6ba44d02f9ada0110e3d47cca3330c81f4aa608f1143eb
  # patches:
  #   - 0001-Apply-upstream-cross-compilation-patch.patch  # [build_platform != target_platform]

build:
  skip: true  # [py<37]
  script:
    - cargo patch  # [build_platform != target_platform]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - cargo-bundle-licenses
    - cargo-patch                            # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python


test:
  imports:
    - sqlglotrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  dev_url: https://github.com/tobymao/sqlglot/tree/main/sqlglotrs
  summary: SQLGlot tokenizer implementation in Rust
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
