{% set name = "sqlglotrs" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglotrs-{{ version }}.tar.gz
  sha256: 6b906c05f4874f502ce512382f057ef90367156dc39b766242754dcfa1b5e21a

build:
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python

    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - sqlglotrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  dev_url: https://github.com/tobymao/sqlglot/tree/main/sqlglotrs
  summary: SQLGlot tokenizer implementation in Rust
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
