schema_version: 1

context:
  name: sqlglotrs
  version: "0.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqlglotrs-${{ version }}.tar.gz
  sha256: 2b9a23c580d82be2388ee23496230cfc667f280ed0ed7eaa099d0da8d718cbf2

build:
  number: 0
  script:
    - if: build_platform != target_platform
      then: cargo patch
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.4,<2.0
        - cargo-patch
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - sqlglotrs
      pip_check: true

about:
  summary: SQLGlot tokenizer implementation in Rust
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  homepage: https://github.com/tobymao/sqlglot
  repository: https://github.com/tobymao/sqlglot/tree/main/sqlglotrs

extra:
  recipe-maintainers:
    - thewchan
